version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://sso.circusstreet.localhost/metadata.xml
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://sso.circusstreet.localhost/login_check
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://security.circusstreet.localhost/logout
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8081:8080"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php
